name:                xmonad-config
version:             0.17.2
github:              "byhowe/xmonad"
license:             BSD3
author:              "Ömer Faruk Çavuş"
maintainer:          "byhowe@proton.me"
copyright:           "2023 Ömer Faruk Çavuş"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/byhowe/xmonad#readme>

dependencies:
- base >= 4.7 && < 5
- data-default-class
- bytestring
- containers
- directory
- filepath
- random
- process
- unix
- X11
- xmonad
- xmonad-contrib
- xmobar

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  xmonad:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-config
